### ISSUE TITLE
nice solution

### ISSUE THREAD

**Issue by tmeidinger** [markus-k/go-echarger-telegraf#1]
Wouldn't be telegrafs processors.converter approach an alternative solution?

e.g.
[[processors.converter]]
  namepass = "go-echarger"
  [processors.converter.fields]
  integer = ["rbc", "rbt", "car", "amp", "err", "ast", "alw", "stp", "cbl", "pha", "tmp", "dws", "dwo", "adi", "uby", "eto", "wst", "txi", "wen", "tof", "tds", "lbr", "aho", "afi", "azo", "ama", "ust", "r1x", "dto", "nmo"]

**Comment by markus-k** [comment]
If that does the job, that'd be a way better solution indeed! I'll check it out.

**Comment by markus-k** [comment]
Seems to do the job. You need to specify all json fields as string fields, and convert them to floats later (or there will be type collisions with existing databases). I'll remove the python server and add my Grafana dashboard later. Thank you for the suggestion!
